name: Tests for Main Branch

# Ce workflow ne se déclenche que sur la branche 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Etape 1 : Récupération du code depuis le dépôt
    - uses: actions/checkout@v2

    # Etape 2 : Configuration de l'environnement Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Etape 3 : Installation des dépendances à partir du fichier requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Etape 4 : Exécution des tests Django
    - name: Run tests
      run: |
        python manage.py test

    # Etape 5 : Vérification du style de code (optionnel, mais recommandé)
    - name: Check code style with flake8
      run: |
        pip install flake8
        flake8 .
